// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1XVfPER8ocls3-6hsIXcb85VM9qdmSIo',
    appId: '1:670597760605:web:7a9b821b6b1bfb68f9efb4',
    messagingSenderId: '670597760605',
    projectId: 'apple-ecommerce1',
    authDomain: 'apple-ecommerce1.firebaseapp.com',
    storageBucket: 'apple-ecommerce1.appspot.com',
    measurementId: 'G-56XYN5ZDYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA2e0GuCBFiEHCpntOoAm82etWjLfcelg',
    appId: '1:670597760605:android:c14ae14bb5e50f08f9efb4',
    messagingSenderId: '670597760605',
    projectId: 'apple-ecommerce1',
    storageBucket: 'apple-ecommerce1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF7kR2TXSUEE3m9niD9jDafUG9mFtyW0o',
    appId: '1:670597760605:ios:2ac010d87b83fd89f9efb4',
    messagingSenderId: '670597760605',
    projectId: 'apple-ecommerce1',
    storageBucket: 'apple-ecommerce1.appspot.com',
    iosBundleId: 'lk.miracle.apple',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF7kR2TXSUEE3m9niD9jDafUG9mFtyW0o',
    appId: '1:670597760605:ios:8a49f22c75509881f9efb4',
    messagingSenderId: '670597760605',
    projectId: 'apple-ecommerce1',
    storageBucket: 'apple-ecommerce1.appspot.com',
    iosBundleId: 'com.example.appleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1XVfPER8ocls3-6hsIXcb85VM9qdmSIo',
    appId: '1:670597760605:web:e7eb1277ec8f3d4ef9efb4',
    messagingSenderId: '670597760605',
    projectId: 'apple-ecommerce1',
    authDomain: 'apple-ecommerce1.firebaseapp.com',
    storageBucket: 'apple-ecommerce1.appspot.com',
    measurementId: 'G-R15T3K4QY3',
  );
}
